### ISSUE TITLE
Is `InChI=1S/B2H6/c1-3-2-4-1/h1-2H2` valid InChI?

### ISSUE THREAD

**Issue by merkys** [metamolecular/inchi-grammar#7]
Among the InChI strings in `strings.txt`, there is one which looks suspicious:
https://github.com/metamolecular/inchi-grammar/blob/a3945daa30e719535363ac5309d4deac9a3106da/strings.txt#L25

It is syntactically correct, but connections block uses atom indices greater than 2 which might mean hydrogen atoms (this looks unusual to me). Open Babel v2.3.2 does not seem to understand bonds with hydrogens in connections block:
```
$ echo 'InChI=1S/B2H6/c1-3-2-4-1/h1-2H2' | obabel -i inchi -o smi
==============================
*** Open Babel Warning  in InChI code
  For InChI=1S/B2H6/c1-3-2-4-1/h1-2H2
  Problems/mismatches: Mobile-H( Charge(s): Do not match)
[BH3-].[BH3-]	
1 molecule converted
```
On the other hand, Open Babel v3.0.0 seems to understand these bonds, but still complains about problems with mobile H:
```
$ echo 'InChI=1S/B2H6/c1-3-2-4-1/h1-2H2' | obabel -i inchi -o smi
==============================
*** Open Babel Warning  in InChI code
  For InChI=1S/B2H6/c1-3-2-4-1/h1-2H2
  Problems/mismatches: Mobile-H( Charge(s): Do not match)
[BH2-]1[H][BH2-][H]1	
1 molecule converted
```

**Comment by rapodaca** [comment]
It is produced from InChI v1.06 ([draw bridged B2H6](https://metamolecular.com/inchi-wasm/)) and was taken directly from one of the InChI documentation set.

**Comment by merkys** [comment]
Thanks for clarification, this was new to me.

**Comment by rapodaca** [comment]
Yes, one of the advantages of a test suite paired with a grammar is that strange cases surface pretty quickly. Glad This clarified things.
